### ISSUE TITLE
Request to rename pypi package

### ISSUE THREAD

**Issue by ssbarnea** [malekhrv/jenkinshash#1]
Please read https://github.com/pypa/warehouse/issues/4294 and please understand that this request came after we got multiple users confused about the module name overlapping.

If package would be renamed to something like `jenkinshash` and match the module name, further confusion could be avoided. Thanks.

**Comment by ssbarnea** [comment]
@malekhrv ping

**Comment by malekhrv** [comment]
@ssbarnea will fix

**Comment by malekhrv** [comment]
fixed.
